### ISSUE TITLE
Single line comment regex

### ISSUE THREAD

**Issue by cortopy** [Microsoft/TypeScript-TmLanguage#254]
In Atom, single line comments are not parsed correctly. In this editor there are certain TODO keywords that get highlighted if present. However, in typescript files this doesn't happen.

I don't know the other editors that this repo supports, so I was wondering if the following PR would be acceptable for TypeScript.YAML-tmLanguage

```yaml
comment-line:
    name: comment.line.ts
    begin: "//"
    end: '$'
```
