### ISSUE TITLE
Template string highlighting not working in Sublime, Atom, VSCode

### ISSUE THREAD

**Issue by admosity** [Microsoft/TypeScript-TmLanguage#335]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.6 / latest

VSCode:
![image](https://cloud.githubusercontent.com/assets/4655972/19730783/4b619224-9b69-11e6-91d1-d95bca1546d3.png)

Atom:
![image](https://cloud.githubusercontent.com/assets/4655972/19730825/702e48d6-9b69-11e6-8f23-bb12938e9be3.png)

Sublime:
![image](https://cloud.githubusercontent.com/assets/4655972/19730852/81cc0ab0-9b69-11e6-8716-cb7b5dda451a.png)

**Code**

```ts
let someInterp:string = 'blah';
let someObject:any = { something: 'hello' };
let someTemplateString:string = `not working ${someInterp} ${someObject.something}`;
```

**Comment by sheetalkamat** [comment]
This is the theme issue. Other grammars handle the template strings similarly and the embedded expressions are scoped for themes to handle.

**Comment by admosity** [comment]
Thanks. PSA for others having this issue at least for atom, you can add the following to your stylesheet to get some highlighting:

```less
  .source.tsx, .source.ts {
    .string.template {
      .variable {
        color: white;
      }
      .punctuation.accessor {
        color: red;
      }
      .template-expression {
        &.begin {
          color: #f92672;
        }
        &.end {
          color: #f92672;
        }
      }
    }
  }
```

So now my highlighting looks like this on atom:
![image](https://cloud.githubusercontent.com/assets/4655972/19771804/2bee2fdc-9c32-11e6-9b44-8b26e9c67141.png)
