### ISSUE TITLE
JS ternary expression not colored correctly

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript-TmLanguage#81]
Under vscode master (0.10.9) with language mode JavaScript.

![ternary](https://cloud.githubusercontent.com/assets/2193314/12963913/0eee1674-d002-11e5-8d01-08f8609b26e1.png)

`'amd64'` has classes: token block decl expr function meta single string ts var var-single-variable js
`'i386'` has classes: token **annotation** block decl expr function meta single string ts type var var-single-variable js

`annotation` scope is causing the following theme style to be applied:

```css
.monaco-editor.vs-dark.vscode-theme-colorful-defaults-themes-dark_plus-tmTheme .token.var.annotation.type.js {
    color: rgba(78, 201, 176, 1);
}
```
